config/routes.rb
Rails.application.routes.draw do
  #resources :tweets
  resources :tweets, :only => [:index, :update]
  get '/auth/:provider/callback', to: 'sessions#create'
  root to: "tweets#index"
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  def self.get_read_tweets(user_id, tweet_user_id, tweet_ids)
    read_tweets = where("internal_user_id =? and tweet_user_id=? and tweet_id IN (?) and read =?", user_id, tweet_user_id, tweet_ids, true)
  end

  def self.find_or_create_by(internal_user_id, tweet_id, tweet_user_id, read = true)
    user_tweet = where(internal_user_id: internal_user_id, tweet_id: tweet_id).first_or_create() do |user_tweet|
      user_tweet.tweet_user_id = tweet_user_id
      user_tweet.read = read
    end
    user_tweet
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(twitter_user_id: auth_hash.uid).first_or_create() do |user|
      user.name = auth_hash.info.nickname
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:logged_on_user_id]) if session[:logged_on_user_id]
  end
  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:logged_on_user_id] = @user.id
    session[:twitter_user_token] = auth_hash.credentials.token
    session[:twitter_user_secret] = auth_hash.credentials.secret
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:logged_on_user_id)
      session.delete(:twitter_user_token)
      session.delete(:twitter_user_secret)
      flash[:success] = "Sucessfully logged out!"
    end
    redirect_to root_path
  end

  protected
 
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_search_text, only: [:index]

  # GET /tweets
  # GET /tweets.json
  def index
    #flash[:notice] = ''
    if (@search_text)# check user is logged in before trying to perform search
      if (current_user)
        @twitter_user_name = @search_text

        if not current_user
          flash[:notice] = 'You must login before performing search'
          redirect_to root_path
        end
        twitter_user_obj = get_twitter_user_obj(@twitter_user_name)

        @twitter_user_id = twitter_user_obj.id if twitter_user_obj
        tweets_total = [twitter_api_result_limitation, twitter_user_obj.statuses_count].min if twitter_user_obj
        if @twitter_user_id
          session[:current_searched_twitter_user_id] = @twitter_user_id

          @tweets = get_tweets(@twitter_user_name, @page, tweets_per_call_count)
          if not @tweets or @tweets.count == 0
            flash[:notice] = "The user #{@twitter_user_name} has no tweets"
          end

          read_tweets = Tweet.get_read_tweets(current_user.id, @twitter_user_id,@tweets.map(&:id)).to_a
          puts "read_Tweets count is " + read_tweets.count.to_s

          @tweets_hash = @tweets.map { |tweet| tweet.attrs["read"] = false; [tweet.id.to_s, tweet] }.to_h

          mark_read_tweets(@tweets_hash, read_tweets)

          @tweets = @tweets_hash.values
          @page_results = WillPaginate::Collection.create(@page, tweets_per_call_count, tweets_total) do |pager|
            pager.replace(@tweets)
          end

          if not @tweets_hash.any? { |id, tweet| not tweet.attrs["read"]}
            flash[:notice] = "The user #{@twitter_user_name} has no unread tweets"
          else
            flash[:notice] = "Tweets from #{@twitter_user_name}"
          end
        else
          flash[:notice] = "The Twitter user #{@twitter_user_name} was not found"
          redirect_to root_path
          if session.key?(:current_searched_twitter_user_id)
            session.delete(:current_searched_twitter_user_id)
          end
          @tweets = false
        end
      else
        redirect_to root_path
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    tweet_id = tweet_params[:tweet_id].to_s

    Tweet.find_or_create_by(current_user.id, tweet_id, session[:current_searched_twitter_user_id].to_s)
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  private

  def twitter_client

    if session.key?(:twitter_user_token)
      @twitter_client ||= Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV['TWITTER_KEY']
        config.consumer_secret     = ENV['TWITTER_SECRET']
        config.access_token        = session[:twitter_user_token]
        config.access_token_secret = session[:twitter_user_secret]
      end
    else
      false
    end

  end

  # helper method to get all tweets in bulks
  def collect_with_max_id(collection=[], max_id=nil, &block)
    response = yield(max_id)
    collection += response
    response.empty? ? collection.flatten : collect_with_max_id(collection, response.last.id - 1, &block)
  end

  # returns an array of all tweets by the given user
  def get_all_tweets(twitter_user_name)
    collect_with_max_id do |max_id|
      options = {count: 200, include_rts: true}
      options[:max_id] = max_id unless max_id.nil?
      twitter_client.user_timeline(twitter_user_name, options)
    end
  end

  # return the count amount of tweets in the given page
  def get_tweets(twitter_user_name, page, count)
    begin
      tweets_arr = twitter_client.user_timeline(twitter_user_name, exclude_replies: true, count: count, page: page)
    rescue => e
      tweets_arr = []
    end

    #tweets_hash = tweets_arr.map { |tweet| [tweet.id, tweet] }.to_h
  end

  # gets the twitter user obj according to given user name
  def get_twitter_user_obj(user_name)
    begin
      user_result = twitter_client.user(user_name)
    rescue Twitter::Error::NotFound => e
      user_result = nil
    rescue Twitter::Error::Forbidden => e
      user_result = nil
    end
    user_result
  end

  # gets a hash of tweets and array of read tweets from DB and marks the tweets in the hash as read for relevant tweets
  def mark_read_tweets(all_tweets_hash, read_tweets_arr)
    read_tweets_arr.each do |tweet|
      all_tweets_hash[tweet.tweet_id.to_s].attrs["read"] = true
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_search_text
      @search_text = params[:term]
      if params.key?(:page)
        @page = params[:page]
      else
        @page = 1
      end
    end

    def set_tweet_id
      @tweet_id = params[:tweet_id]
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:term, :tweet_id, :page)
    end

  def tweets_per_call_count
    20
  end

  def twitter_api_result_limitation
    3200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand nav navbar-nav navbar-left" href="#">Tweets</a>-->
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <%= form_tag(tweets_path, method: :get) do %>
      <ul class="navbar-brand nav navbar-nav navbar-left">
        <!--<li><%= link_to 'Home', root_path %></li>-->
        <% if current_user %>
            <li><a>Signed in as <%= current_user.name %></a></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign in with Twitter to search for tweets", "/auth/twitter" %></li>
        <% end %>
      </ul>
      <ul class="navbar-brand nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= text_field_tag :term, params[:term], :class => "search_box", placeholder: "Search Tweets By User" %></li>
        <li><%= submit_tag 'Search', name: nil, :class => "button"  %></li>
            <%end%>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Twitter Feed" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render "layouts/navigation" %>
  <div class="container-fluid">
    <%= yield %>
  </div>

  </body>
</html>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :url %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/tweets/index.html.erb
<h1 id="notice"><%= notice %></h1>


<% if @search_text and current_user and @twitter_user_id %>
  <table>
    <thead>
    <tr>
      <th colspan="17">Mark As Read</th>
      <th colspan="5">Tweet</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @tweets.each do |tweet| %>
        <tr id=tr_<%=tweet.id%> "result_tr" <%if tweet.attrs["read"] then%>style="display: none;"<%else%> style="table-row"<%end%>">
        <td colspan="17" align="center"><input type="checkbox" value=<%=tweet.id%> onclick="update_read_state(this.value);" <%if tweet.attrs["read"] then %> checked="true" <%end%> /></td>
        <td colspan="5"><%= auto_link(tweet.full_text) %></td>
        <td><%= tweet.created_at.strftime("%a, %d %b %Y %H:%M:%S") %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
    <%= will_paginate @page_results , :class => "my_pagination"%>
<% end %>
<br>